### ISSUE TITLE
appveyor: add location of datalad installer results to PATH

### ISSUE THREAD

**Issue by mih** [datalad/datalad-extension-template#22]
Something like that in `.appveyor.yml`

```
- sh: export PATH=$(dirname ${TMPDIR}/dl-build*/git-annex*/git-annex):$PATH
```

Otherwise a git-annex autobuild flavor installed with the datalad-installer will not be accessible to the tests.

Demo https://github.com/mih/datalad-mihextras/blob/670dd3ff92cc5a650420037a04ee2886149dee8e/.appveyor.yml#L164

**Comment by mih** [comment]
Probably better done on a case-by-case basis (hence in docs by default) using the matching installer feature:

```yaml
  - sh: "[ -n \"${INSTALL_GITANNEX}\" ] && datalad-installer -E ${HOME}/dlinstaller_env.sh --sudo ok ${INSTALL_GITANNEX}"
  # add location of datalad installer results to PATH
  - sh: "[ -f ${HOME}/dlinstaller_env.sh ] && . ${HOME}/dlinstaller_env.sh || true"
```
